spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbstore
    username: postgres
    password: 196120
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Met à jour le schéma automatiquement (ATTENTION: 'validate' en prod)
    show-sql: true # Affiche les requêtes SQL dans la console pour le débogage
    properties:
      hibernate:
        "[format_sql]": true # Formate le SQL pour qu'il soit lisible
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuration JWT (JSON Web Token) pour la sécurité
app:
  jwt:
    # Clé secrète pour signer les tokens (Doit être longue et complexe)
    secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
    # Durée de vie du token en millisecondes (86400000 = 24 heures)
    expiration: 86400000

  # Numéro WhatsApp du vendeur pour les commandes (Format international sans +)
  whatsapp-number: "2250707070707"

  # Configuration du stockage des images
  storage:
    location: "uploads"

server:
  port: 8080
  servlet:
    context-path: /api # Toutes les URLs commenceront par /api (ex: /api/products)
