spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbstore
    username: postgres
    password: 196120
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update # Met à jour le schéma automatiquement (ATTENTION: 'validate' en prod)
    show-sql: true # Affiche les requêtes SQL dans la console pour le débogage
    properties:
      hibernate:
        "[format_sql]": true # Formate le SQL pour qu'il soit lisible
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuration JWT (JSON Web Token) pour la sécurité
app:
  jwt:
    # Clé secrète pour signer les tokens (Doit être longue et complexe)
    secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
    # Durée de vie du token en millisecondes (86400000 = 24 heures)
    expiration: 86400000

  # Numéro WhatsApp du vendeur pour les commandes (Format international sans +)
  whatsapp-number: "2250707070707"

  # Configuration du stockage des images
  storage:
    location: "uploads"

google:
  sheets:
    application-name: "Sucre Store API"
    credentials-file-path: "classpath:credentials.json"
    spreadsheet-id: "1qcfPhb_dnSiippTY9JkNXMpDkYn5oKn0b7TTWPJkIP8" # ID extrait de votre URL
    sync-rate: 60000 # Taux de synchronisation en millisecondes (60000ms = 1 minute)

server:
  port: 8080
  # servlet:
  # context-path: /api # RETIRÉ : Cause un double préfixe /api/api car les contrôleurs ont déjà @RequestMapping("/api")
